package com.siblinks.ws.util;

public class Parameters {
    public static final String ID = "id";
    public static final String FROM = "from";
    public static final String TO = "to";
    public static final String CID = "cid";
    public static final String AUTHOR_ID = "authorId";
    public static final String IMAGE = "image";
    public static final String USER_ID = "userid";
    public static final String USER_NAME = "username";
    public static final String PASSWORD = "password";
    public static final String USER_TYPE = "userType";
    public static final String IMAGE_URL = "imageUrl";
    public static final String DEFAULT_SUBJECT_ID = "defaultSubjectId";
    public static final String FIRST_NAME = "firstName";
    public static final String LAST_NAME = "lastName";
    public static final String REMEMBER_ME="remember-me";
    public static final String GET_USER_BY_USERNAME = "GET_USER_BY_USERNAME";
    public static final String USERID = "userid";
    public static final String MAJOR_OF_USER = "MAJOR_OF_USER";
    public static final String ACTIVITY_OF_USER = "ACTIVITY_OF_USER";
    public static final String HELP_OF_USER = "HELP_OF_USER";
    public static final String MAJORS = "majors";
    public static final String ACTIVITY = "activity";
    public static final String HELP = "help";
    public static final String SUBJECT_ID = "subject_id";
    public static final String URLREVIEW = "urlReview";
    public static final String LIKE = "like";
    public static final String RATE = "rate";
    public static final String LEVEL = "level";
    public static final String COUNT = "count";
    public static final String RULES = "rules";
    public static final String TYPE_PLAY_SOLO_VIDEO = "0";
    public static final String LIMIT = "limit";
    public static final String OFFSET = "offset";
    public static final String NEWEST = "newest";
    public static final String ANSWERED = "answered";
    public static final String UNANSWERED = "unanswered";
    public static final String SUBCRIBE = "Subcribe";
}
